"""empty message

Revision ID: c2a239ddbc2e
Revises: 
Create Date: 2020-09-13 22:13:50.682159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2a239ddbc2e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('record',
    sa.Column('sn', sa.String(length=48), nullable=False),
    sa.Column('cert', sa.Binary(), nullable=False),
    sa.Column('issuer_sn', sa.String(length=48), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('sn')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('record')
    # ### end Alembic commands ###
